### ISSUE TITLE
Añadir fichas 

### ISSUE THREAD

**Issue by asierraperez** [asierraperez/COD-Proyecro_3enraya#12]
fichas en formato svg

**Comment by TataFV** [comment]
Añadidas fichas. Son fichas sencillas  ¿ alguna sugerencia de cambio de estilo (color, grosor, tamaño)?. Tengo que investigar la parte responsive para centrar la posición.

**Comment by asierraperez** [comment]
Está genial, además arreglaste el problema de que colocaba las fichas al revés, por lo que perfecto.
Igual estaba bien poner cada una de un color y un poco más grandes. También se puede ver para centrarlas un poco en las casillas. pero vamos que lo básico ya estaría.
Activé las pages así que si quieres ver el resultado de como está quedando lo tienes aquí: [https://asierraperez.github.io/COD-Proyecro_3enraya/](url)

**Comment by damiancastelao** [comment]
Muy buena comunicación! Lo estáis haciendo genial.

**Comment by TataFV** [comment]
![3enRaya_Prueba de Color](https://user-images.githubusercontent.com/92530903/158661999-b1f9d8cc-3dd6-4048-8591-891a8e04eb6e.PNG)

Tocando el SVG conseguí buenos resultados: con el **viewBox** las centré,   con **width** y **height** modifiqué el tamaño, con **fill** cambié el color. Esperaba que con **stroke-width** pudiese modificar el trazo del círculo pero no obtuve resultados. ¿alguna idea? ¿Habría que manipular directamente el path?

**Comment by asierraperez** [comment]
Yo lo veo bien. El problema es que ahora, al ser las fichas mas grandes, las casillas se cambian de tamaño e incluso se salen del fondo. en pantallas pequeñas, tipo portátiles, pasa esto. Ya me pongo yo con ello

![Problema proyecto 2](https://user-images.githubusercontent.com/92427430/158969526-0014c2fa-5225-4fb7-b8b2-4b4d67e14210.PNG)

En pantallas pequeñas, tipo portátiles, pasa esto. Ya me pongo yo con ello
