### ISSUE TITLE
Tablero 

### ISSUE THREAD

**Issue by asierraperez** [asierraperez/COD-Proyecro_3enraya#3]
Crear el tablero del 3 en raya en el HTML

**Comment by TataFV** [comment]
Añadido tablero en el HTML. Le puse un nombre básico a los ID de las posiciones del tablero. ¿Necesitas que los cambie?

**Comment by TataFV** [comment]
Después del cambió de div id a div class="casillas" las reglas CSS relacionadas con estos ids dejaron de funcionar  y el tablero sufrió una pequeña modicación respecto al diseño original. Para reestablecerlo fué necesario eliminar en el CSS  las reglas de estilo de estos ids y sustituirlos por una regla de estilo nueva que modificase de nuevo las casillas afectadas.
