### ISSUE TITLE
Cambiar id de casillas por class

### ISSUE THREAD

**Issue by asierraperez** [asierraperez/COD-Proyecro_3enraya#8]
En vez de asignar un "id" a cada casilla (p.ej en la primera casilla "id=d01"), creo que es más práctico que las declares como "class", para que todas sean de la clase "casilla" por ejemplo. Así también me es más fácil modificar el js.

**Comment by asierraperez** [comment]
Cuando lo termines, prueba a hacer un pull request aqui en github, si no no me entero de que se modificó y que no

**Comment by asierraperez** [comment]
Acabo de modificar el js. Ponle de nombre a de clase "casillas"

**Comment by TataFV** [comment]
Los cambios fueron realizados.
