### ISSUE TITLE
Hacer llamadas a scripts en el html

### ISSUE THREAD

**Issue by asierraperez** [asierraperez/COD-Proyecro_3enraya#9]
Hay que hacer las llamadas a la carpeta de scripts en en html

**Comment by TataFV** [comment]
Como aún no estaba realizada esta tarea aún no tenía los scripts en mi rama feature_svg y para ver si funcionaban los svg los creé y luego bno me di cuenta y los subí al subir todo. Por eso están commiteados y luego borrados los cambios mios realizados en el index.html.
